version: "2"

services:
  user-service:
    build: spring-boot/spring-boot-user
    ports:
      - "8011:8011"
    environment:
      spring.profiles.active: microservice
      spring.datasource.url: jdbc:mysql://mysql:3306/waber_user
      spring.rabbitmq.host: rabbitmq
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.user-service.rule=PathPrefix(`/api/users`) || PathPrefix(`/api/passengers`) || PathPrefix(`/api/drivers`)"
      - "traefik.http.routers.user-service.entrypoints=web"
      - "traefik.http.routers.user-service.service=user-service"
      - "traefik.http.services.user-service.loadbalancer.server.port=80"
      - "traefik.http.routers.user-service.priority=1"
    memswap_limit: -1

  match-service:
    build: spring-boot/spring-boot-match
    environment:
      spring.profiles.active: microservice
      spring.datasource.url: jdbc:mysql://mysql:3306/waber_match
      spring.rabbitmq.host: rabbitmq
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.match-service.rule=PathPrefix(`/api/users/{passengerId:[0-9]+}/matches`) || PathPrefix(`/api/matches`)"
      - "traefik.http.routers.match-service.entrypoints=web"
      - "traefik.http.routers.match-service.service=match-service"
      - "traefik.http.services.match-service.loadbalancer.server.port=80"
      - "traefik.http.routers.match-service.priority=2"

  trip-service:
    build: spring-boot/spring-boot-trip
    environment:
      spring.profiles.active: microservice
      spring.data.mongodb.uri: mongodb://mongodb:27017/waber_trip
      spring.rabbitmq.host: rabbitmq
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.trip-service.rule=PathPrefix(`/api/trips`) || PathPrefix(`/api/users/{passengerId:[0-9]+}/trips`)"
      - "traefik.http.routers.trip-service.entrypoints=web"
      - "traefik.http.routers.trip-service.service=trip-service"
      - "traefik.http.services.trip-service.loadbalancer.server.port=80"
      - "traefik.http.routers.trip-service.priority=3"

#  payment-service:
#    build: spring-boot/spring-boot-payment
#    environment:
#      spring.profiles.active: microservice
#      spring.data.mongodb.uri: mongodb://mongodb:27017/waber_payment
#      spring.rabbitmq.host: rabbitmq
#    labels:
#      - "traefik.enable=true"
#      - "traefik.http.routers.payment-service.rule=PathPrefix(`/api/payments`)"
#      - "traefik.http.routers.payment-service.entrypoints=web"
#      - "traefik.http.routers.payment-service.service=payment-service"
#      - "traefik.http.services.payment-service.loadbalancer.server.port=80"
#    memswap_limit: -1
  broker:
    build: spring-boot/spring-boot-broker
    environment:
      spring.rabbitmq.host: rabbitmq
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.broker.rule=PathPrefix(`/broker`) || PathPrefix(`/topic`)"
      - "traefik.http.routers.broker.entrypoints=web"
      - "traefik.http.routers.broker.service=broker"
      - "traefik.http.services.broker.loadbalancer.server.port=80"

networks:
  default:
    external:
      name: ddd-benchmark-waber_infra

