version: "3"

services:
  mongodb:
    image: mongo
    command: --bind_ip 0.0.0.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-db-data:/data/db
    networks:
      - infra

  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1qaz2wsx
    ports:
      - "3306:3306"
    volumes:
      - mysql-db-data:/var/lib/mysql
      - "./init-databases.sql:/data/application/init-db.sql"
    command:
      - "--init-file=/data/application/init-db.sql"
    networks:
      - infra

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: waber
      RABBITMQ_DEFAULT_PASS: waber
      RABBITMQ_DEFAULT_VHOST: /waber
    networks:
      - infra

  traefik:
    image: traefik:v2.3
    command:
      - "--entryPoints.web.address=:80"
      - "--api.insecure=true"
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - infra

  jaeger:
    image: jaegertracing/all-in-one
    ports:
      - "14250:14250"
      - "16686:16686"
    networks:
      - infra


networks:
  infra:

volumes:
  mongo-db-data:
  mysql-db-data:
