waber:
  client:
    user-service:
      scheme: http
      host: user-service
      port: 80
    match-service:
      scheme: http
      host: match-service
      port: 80
    trip-service:
      scheme: http
      host: trip-service
      port: 80
    payment-service:
      scheme: http
      host: payment-service
      port: 80