waber:
  client:
    user-service:
      scheme: http
      host: localhost
      port: 80
    match-service:
      scheme: http
      host: localhost
      port: 80
    mysql:
      scheme: jdbc:mysql
      host: localhost
      port: 3306
    mongo:
      host: localhost
      port: 27017
