waber:
  client:
    user-service:
      scheme: "http"
      host: "localhost"
      port: 80
    match-service:
      scheme: "http"
      host: "localhost"
      port: 80
  distance:
    strategy: "linear"